name: Build resume with Typst

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/build-resume.yml"
      - "scripts/resume.json"
      - "scripts/resume.typ"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: latest

      - name: Compile pdf
        run: typst compile --font-path ./fonts --root ./ scripts/resume.typ static/resume.pdf

      - name: Commit resume
        run: |
          git config --global user.name "alpoi[bot]"
          git config --global user.email "me@angus.buzz"
          git add static/resume.pdf
          git commit -m "Update resume"
          git push
